[tool.poetry]
name = "ultimascraper"
version = "8.0.0"
description = ""
authors = ["DIGITALCRIMINAL <89371864+DIGITALCRIMINALS@users.noreply.github.com>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "~3.10.1"
requests = "^2.26.0"
beautifulsoup4 = "^4.10.0"
win32-setctime = "^1.0.4"
python-socks = {extras = ["asyncio"], version = "^2.0.1"}
python-dateutil = "^2.8.2"
mergedeep = "^1.3.4"
SQLAlchemy = "^1.4.20"
alembic = "^1.7.5"
tqdm = "^4.62.3"
selenium = "^4.1.0"
selenium-wire = "2.1.2"
user-agent = "^0.1.10"
aiohttp = "^3.8.1"
aiohttp-socks = "^0.7.1"
rich = "^10.16.1"
orjson = "^3.6.5"

lxml = { version = "^4.7.1", optional = true }

[tool.poetry.extras]
performance = ["lxml"]

[tool.poetry.dev-dependencies]
black = {version = "^21.12b0", allow-prereleases = true}
pyinstaller = {version = "^5.0.1", markers = "sys_platform == 'win32'"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
